language: python

sudo: required

services:
  - docker

env:
  global:
    - IMAGE_NAME=fin-jupyter
    - CONTAINER_NAME=fin-jupyter

script:
  - travis_retry bash test_docker.sh

notifications:
  email: true
  slack:
    secure: "nidoMFNrNaKpix3iLx/qvg3+aqZNT4+JPVtNeuSnczitr3KrM5V/p0INsnJVtuleAnirJ5l31RHcpHYlqlFAgJ1R9Ekb4Es+vL4YZi1blKBTk8ZHecvp3TOk0nJOeHtBX9axLUn765NZnk80YChj7ZWkFdIx59KiK1FgXu5H+gyKb1wKVOo9+UeOM++eC3kikJ/BOanaL4r1UtekrHve5RqUJdJ4xf6bZ69iHtV2YJBxjP7w1vlEigUnN7qtVFlJdTUWegsM96lxjtXbWw79zHYhU+MmIPROtvG2KYayViTtw1Qz6jTsXjLObdoF7un04KRABtLboAKQ+dJIck0xQpYr/3zplrFm3tm+9lxEE8nFXipeky11xt4iXhK1qAv7VP+35Mvb+t2SYLsJW4ofJklghxOSQoSkk9/9ets3nq5zaR5JAWvuTIpJtZGAzhMlSSVX3qlDtHjcrmp9koOFByNVRouICyEaWW/4YYV7r4GbyLdJzbMpBWwE9WWXSXEBXHZ64kK3eZl+vpo3sKh9cAggZLiDVTEvoNJuVe8pLIgXq2NHN+QxNpLy9DaIMxZKT+mjnaZAUL4ogeN+iyE71sJjv48ffCsu96n4h5fYcB3w5OgmtPPXRb2NDOP/DMI78TnfmvZRw8NKvCjcneUcTjYz8R2Xuz2V3ij13r7yv1M="
